import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import AppSidebar from "./fragments/AppSidebar";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} bg-gray-50 dark:bg-gray-950 antialiased p-3 w-full`}
      >
        <SidebarProvider>
          <AppSidebar />
          <main className="flex flex-col w-full h-screen">
            <SidebarTrigger className="bg-gray-600 hover:bg-gray-500 hover:text-white text-white cursor-pointer" />
            {children}
          </main>
        </SidebarProvider>
      </body>

    </html>
  );
}
